export interface Program {
  id: string;
  title: string;
  category:
    | "undergraduate"
    | "graduate"
    | "doctoral"
    | "online"
    | "professional";
  degree: string;
  duration: string;
  description: string;
  features: string[];
  career: string[];
  image?: string;
  featured?: boolean;
}

export const programs: Program[] = [
  {
    id: "ba-business",
    title: "Business Administration",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Comprehensive business education covering management, finance, marketing, and entrepreneurship to prepare future business leaders.",
    features: [
      "Modern curriculum",
      "Industry internships",
      "Case studies",
      "Business simulations",
      "Career counseling",
    ],
    career: [
      "Business Analyst",
      "Marketing Manager",
      "Entrepreneur",
      "Financial Advisor",
    ],
    featured: true,
  },
  {
    id: "ba-computer-science",
    title: "Computer Science",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Cutting-edge computer science program focusing on software development, algorithms, and emerging technologies.",
    features: [
      "Hands-on projects",
      "Industry partnerships",
      "Research opportunities",
      "Modern labs",
      "Internship programs",
    ],
    career: [
      "Software Developer",
      "Data Scientist",
      "System Analyst",
      "IT Consultant",
    ],
    featured: true,
  },
  {
    id: "ba-psychology",
    title: "Psychology",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Explore human behavior and mental processes through comprehensive psychological studies and practical applications.",
    features: [
      "Research labs",
      "Clinical experience",
      "Field work",
      "Case studies",
      "Internship opportunities",
    ],
    career: [
      "Counselor",
      "Research Analyst",
      "HR Specialist",
      "Mental Health Worker",
    ],
  },
  {
    id: "ma-mba",
    title: "Master of Business Administration",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced business administration program designed for professionals seeking leadership roles and strategic management skills.",
    features: [
      "Executive workshops",
      "Global case studies",
      "Leadership development",
      "Networking events",
      "Career placement",
    ],
    career: [
      "CEO",
      "Operations Manager",
      "Strategy Consultant",
      "Business Development",
    ],
    featured: true,
  },
  {
    id: "ma-data-science",
    title: "Data Science",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced data science program focusing on machine learning, big data analytics, and artificial intelligence.",
    features: [
      "Advanced analytics",
      "ML & AI focus",
      "Industry projects",
      "Research opportunities",
      "Tech partnerships",
    ],
    career: [
      "Data Scientist",
      "ML Engineer",
      "Analytics Manager",
      "AI Specialist",
    ],
    featured: true,
  },
  {
    id: "ma-education",
    title: "Education Leadership",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Prepare for educational leadership roles with advanced pedagogy, administration, and policy development skills.",
    features: [
      "Leadership training",
      "Policy analysis",
      "Administrative skills",
      "Field experience",
      "Mentorship program",
    ],
    career: [
      "School Principal",
      "Education Administrator",
      "Policy Advisor",
      "Curriculum Developer",
    ],
  },
  {
    id: "phd-business",
    title: "Business Administration",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral program in business administration focusing on advanced research, theory development, and academic excellence.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Conference attendance",
      "Academic mentorship",
    ],
    career: [
      "University Professor",
      "Research Director",
      "Business Consultant",
      "Policy Researcher",
    ],
  },
  {
    id: "phd-psychology",
    title: "Psychology",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Advanced doctoral program in psychology with specialization in clinical, research, or applied psychology fields.",
    features: [
      "Clinical training",
      "Research opportunities",
      "Publication support",
      "Teaching experience",
      "Professional development",
    ],
    career: [
      "Clinical Psychologist",
      "Researcher",
      "University Professor",
      "Therapist",
    ],
  },
  {
    id: "online-mba",
    title: "Online MBA",
    category: "online",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Flexible online MBA program designed for working professionals seeking to advance their careers without interrupting their work.",
    features: [
      "Flexible schedule",
      "Online resources",
      "Virtual lectures",
      "Student support",
      "Networking opportunities",
    ],
    career: ["Business Manager", "Executive", "Consultant", "Entrepreneur"],
  },
  {
    id: "online-compsci",
    title: "Online Computer Science",
    category: "online",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Comprehensive online computer science program offering the same quality education as on-campus programs.",
    features: [
      "Self-paced learning",
      "Virtual labs",
      "Online support",
      "Career services",
      "Digital resources",
    ],
    career: [
      "Software Developer",
      "Web Developer",
      "System Administrator",
      "IT Specialist",
    ],
  },
  {
    id: "cert-digital-marketing",
    title: "Digital Marketing Certificate",
    category: "professional",
    degree: "Certificate",
    duration: "6 Months",
    description:
      "Professional certificate program in digital marketing covering SEO, social media, content marketing, and analytics.",
    features: [
      "Industry-focused",
      "Practical projects",
      "Expert instructors",
      "Career support",
      "Certificate award",
    ],
    career: [
      "Digital Marketer",
      "SEO Specialist",
      "Content Manager",
      "Social Media Manager",
    ],
  },
  {
    id: "cert-project-management",
    title: "Project Management",
    category: "professional",
    degree: "Certificate",
    duration: "6 Months",
    description:
      "Professional project management certification preparing you for PMP certification and leadership roles.",
    features: [
      "PMP preparation",
      "Real-world projects",
      "Industry standards",
      "Certification support",
      "Career guidance",
    ],
    career: [
      "Project Manager",
      "Program Manager",
      "Operations Manager",
      "Consultant",
    ],
  },
  // Bachelor's Programs from ISTU Price List 2025
  {
    id: "ba-aviation-management",
    title: "Aviation Management",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Comprehensive aviation management program covering airline operations, airport management, and aviation business strategies.",
    features: [
      "Aviation industry focus",
      "Airline operations",
      "Airport management",
      "Aviation regulations",
      "Industry internships",
    ],
    career: [
      "Airline Manager",
      "Airport Operations Manager",
      "Aviation Consultant",
      "Flight Operations Coordinator",
    ],
  },
  {
    id: "ba-political-science",
    title: "Political Science and Public Administration",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Study political systems, public policy, and administrative processes to prepare for careers in government and public service.",
    features: [
      "Political theory",
      "Public policy analysis",
      "Administrative skills",
      "Government internships",
      "Research opportunities",
    ],
    career: [
      "Public Administrator",
      "Policy Analyst",
      "Government Official",
      "Political Consultant",
    ],
  },
  {
    id: "ba-international-relations",
    title: "International Relations",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Explore global politics, diplomacy, and international cooperation to understand complex international dynamics.",
    features: [
      "Diplomatic studies",
      "Global politics",
      "International law",
      "Foreign policy analysis",
      "Study abroad opportunities",
    ],
    career: [
      "Diplomat",
      "International Relations Specialist",
      "Foreign Policy Analyst",
      "International NGO Worker",
    ],
  },
  {
    id: "ba-international-business",
    title: "International Business and Entrepreneurship",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Develop global business skills and entrepreneurial mindset to succeed in international markets and start your own venture.",
    features: [
      "Global business strategies",
      "Entrepreneurship training",
      "Cross-cultural management",
      "Startup support",
      "International internships",
    ],
    career: [
      "International Business Manager",
      "Entrepreneur",
      "Global Trade Specialist",
      "Business Development Manager",
    ],
  },
  {
    id: "ba-international-trade",
    title: "International Trade and Logistics",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Master international trade operations, supply chain management, and logistics to facilitate global commerce.",
    features: [
      "Trade regulations",
      "Supply chain management",
      "Logistics operations",
      "Customs procedures",
      "Industry partnerships",
    ],
    career: [
      "International Trade Specialist",
      "Logistics Manager",
      "Supply Chain Analyst",
      "Customs Broker",
    ],
  },
  {
    id: "ba-management-information-systems",
    title: "Management Information Systems",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Bridge business and technology by learning to design, implement, and manage information systems for organizations.",
    features: [
      "Information systems design",
      "Database management",
      "Business analysis",
      "IT project management",
      "Industry certifications",
    ],
    career: [
      "IT Manager",
      "Business Analyst",
      "Systems Analyst",
      "IT Consultant",
    ],
  },
  {
    id: "ba-economics-finance",
    title: "Economics and Finance",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Study economic principles and financial markets to understand how economies function and make informed financial decisions.",
    features: [
      "Economic theory",
      "Financial analysis",
      "Market research",
      "Investment strategies",
      "Financial modeling",
    ],
    career: [
      "Financial Analyst",
      "Economist",
      "Investment Advisor",
      "Risk Manager",
    ],
  },
  {
    id: "ba-exercise-sports-sciences",
    title: "Exercise and Sports Sciences",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Study human movement, exercise physiology, and sports performance to promote health and athletic excellence.",
    features: [
      "Exercise physiology",
      "Sports performance",
      "Fitness assessment",
      "Athletic training",
      "Research labs",
    ],
    career: [
      "Sports Scientist",
      "Fitness Trainer",
      "Athletic Coach",
      "Exercise Physiologist",
    ],
  },
  {
    id: "ba-health-management",
    title: "Health Management",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Learn to manage healthcare organizations, improve healthcare delivery, and navigate the complex healthcare industry.",
    features: [
      "Healthcare administration",
      "Healthcare policy",
      "Quality management",
      "Healthcare finance",
      "Hospital internships",
    ],
    career: [
      "Healthcare Administrator",
      "Hospital Manager",
      "Health Policy Analyst",
      "Healthcare Consultant",
    ],
  },
  {
    id: "ba-computer-engineering",
    title: "Computer Engineering",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Design and develop computer systems, hardware, and software solutions for modern technological challenges.",
    features: [
      "Hardware design",
      "Software development",
      "Embedded systems",
      "Computer architecture",
      "Industry projects",
    ],
    career: [
      "Computer Engineer",
      "Hardware Engineer",
      "Embedded Systems Engineer",
      "Systems Architect",
    ],
  },
  {
    id: "ba-software-engineering",
    title: "Software Engineering",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Master software development methodologies, system design, and engineering principles to build robust software solutions.",
    features: [
      "Software design",
      "Programming languages",
      "System architecture",
      "Agile methodologies",
      "Team projects",
    ],
    career: [
      "Software Engineer",
      "Software Architect",
      "DevOps Engineer",
      "Technical Lead",
    ],
  },
  {
    id: "ba-cybersecurity-engineering",
    title: "Cyber Security Engineering",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Protect digital systems and networks from cyber threats through advanced security engineering and ethical hacking techniques.",
    features: [
      "Cybersecurity fundamentals",
      "Network security",
      "Ethical hacking",
      "Security protocols",
      "Certification preparation",
    ],
    career: [
      "Cybersecurity Engineer",
      "Security Analyst",
      "Penetration Tester",
      "Security Architect",
    ],
  },
  {
    id: "ba-ai-engineering",
    title: "Artificial Intelligence Engineering",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Develop AI systems, machine learning models, and intelligent solutions to solve complex real-world problems.",
    features: [
      "Machine learning",
      "Deep learning",
      "AI algorithms",
      "Neural networks",
      "AI projects",
    ],
    career: [
      "AI Engineer",
      "Machine Learning Engineer",
      "AI Researcher",
      "Data Scientist",
    ],
  },
  {
    id: "ba-aviation-systems-engineering",
    title: "Aviation Systems and Technologies Engineering",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Design and maintain aviation systems, aircraft technologies, and aerospace solutions for the aviation industry.",
    features: [
      "Aviation systems",
      "Aircraft technology",
      "Aerospace engineering",
      "Aviation safety",
      "Industry partnerships",
    ],
    career: [
      "Aviation Engineer",
      "Aircraft Systems Engineer",
      "Aerospace Engineer",
      "Aviation Technology Specialist",
    ],
  },
  {
    id: "ba-industrial-engineering",
    title: "Industrial Engineering",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Optimize complex systems and processes in manufacturing, logistics, and service industries through engineering principles.",
    features: [
      "Process optimization",
      "Systems engineering",
      "Quality control",
      "Operations research",
      "Industry projects",
    ],
    career: [
      "Industrial Engineer",
      "Process Engineer",
      "Operations Manager",
      "Quality Engineer",
    ],
  },
  {
    id: "ba-management-engineering",
    title: "Management Engineering",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Combine engineering principles with management skills to lead technical teams and manage engineering projects.",
    features: [
      "Engineering management",
      "Project management",
      "Technical leadership",
      "Business skills",
      "Team management",
    ],
    career: [
      "Engineering Manager",
      "Project Manager",
      "Technical Director",
      "Engineering Consultant",
    ],
  },
  {
    id: "ba-law",
    title: "Law",
    category: "undergraduate",
    degree: "Bachelor's",
    duration: "4 Years",
    description:
      "Study legal principles, jurisprudence, and legal systems to prepare for a career in law and legal services.",
    features: [
      "Legal theory",
      "Constitutional law",
      "Civil and criminal law",
      "Legal research",
      "Moot court",
    ],
    career: ["Lawyer", "Legal Advisor", "Judge", "Legal Consultant"],
  },
  // Master's Programs from ISTU Price List 2025
  {
    id: "ma-aviation-systems-technologies",
    title: "Aviation Systems and Technologies",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced study of aviation systems, aircraft technologies, and aerospace engineering for aviation industry professionals.",
    features: [
      "Advanced aviation systems",
      "Aircraft design",
      "Aviation safety",
      "Research projects",
      "Thesis option",
    ],
    career: [
      "Aviation Systems Engineer",
      "Aircraft Design Engineer",
      "Aviation Safety Specialist",
      "Aerospace Researcher",
    ],
  },
  {
    id: "ma-engineering-management",
    title: "Engineering Management",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Develop leadership and management skills for engineering professionals to lead technical teams and manage complex projects.",
    features: [
      "Engineering leadership",
      "Project management",
      "Technical strategy",
      "Business management",
      "Thesis option",
    ],
    career: [
      "Engineering Manager",
      "Technical Director",
      "Project Director",
      "Engineering Consultant",
    ],
  },
  {
    id: "ma-health-management-ms",
    title: "Health Management",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced healthcare administration and management program for healthcare professionals seeking leadership roles.",
    features: [
      "Healthcare leadership",
      "Health policy",
      "Healthcare finance",
      "Strategic planning",
      "Thesis option",
    ],
    career: [
      "Healthcare Administrator",
      "Hospital Director",
      "Health Policy Manager",
      "Healthcare Consultant",
    ],
  },
  {
    id: "ma-cybersecurity-engineering",
    title: "Cybersecurity Engineering",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced cybersecurity engineering program focusing on protecting critical infrastructure and developing secure systems.",
    features: [
      "Advanced security",
      "Threat analysis",
      "Security architecture",
      "Incident response",
      "Thesis option",
    ],
    career: [
      "Cybersecurity Engineer",
      "Security Architect",
      "Security Researcher",
      "Chief Information Security Officer",
    ],
  },
  {
    id: "ma-software-engineering-ms",
    title: "Software Engineering",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced software engineering program focusing on large-scale systems, software architecture, and engineering methodologies.",
    features: [
      "Software architecture",
      "Large-scale systems",
      "Engineering methodologies",
      "Research projects",
      "Thesis option",
    ],
    career: [
      "Senior Software Engineer",
      "Software Architect",
      "Engineering Manager",
      "Technical Lead",
    ],
  },
  {
    id: "ma-renewable-energy-engineering",
    title: "Renewable Energy Engineering",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Design and develop renewable energy systems, sustainable technologies, and clean energy solutions for a sustainable future.",
    features: [
      "Renewable energy systems",
      "Solar and wind technology",
      "Energy storage",
      "Sustainability",
      "Thesis option",
    ],
    career: [
      "Renewable Energy Engineer",
      "Energy Systems Engineer",
      "Sustainability Consultant",
      "Energy Researcher",
    ],
  },
  {
    id: "ma-management-information-systems-ms",
    title: "Management Information Systems",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced MIS program focusing on enterprise systems, business intelligence, and strategic IT management.",
    features: [
      "Enterprise systems",
      "Business intelligence",
      "IT strategy",
      "Data analytics",
      "Thesis option",
    ],
    career: [
      "IT Manager",
      "Business Intelligence Analyst",
      "Systems Architect",
      "IT Director",
    ],
  },
  {
    id: "ma-data-science-engineering",
    title: "Data Science Engineering",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced data science and engineering program focusing on big data, machine learning, and data-driven solutions.",
    features: [
      "Big data technologies",
      "Machine learning",
      "Data engineering",
      "Analytics platforms",
      "Thesis option",
    ],
    career: [
      "Data Engineer",
      "Data Scientist",
      "ML Engineer",
      "Analytics Architect",
    ],
  },
  {
    id: "ma-computer-engineering-ms",
    title: "Computer Engineering",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced computer engineering program focusing on advanced computer systems, hardware design, and embedded systems.",
    features: [
      "Advanced computer systems",
      "Hardware design",
      "Embedded systems",
      "Research projects",
      "Thesis option",
    ],
    career: [
      "Senior Computer Engineer",
      "Hardware Architect",
      "Systems Engineer",
      "Research Engineer",
    ],
  },
  {
    id: "ma-ai-engineering-ms",
    title: "Artificial Intelligence Engineering",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced AI engineering program focusing on deep learning, neural networks, and intelligent system design.",
    features: [
      "Deep learning",
      "Neural networks",
      "AI systems design",
      "Research projects",
      "Thesis option",
    ],
    career: ["AI Engineer", "ML Engineer", "AI Researcher", "AI Architect"],
  },
  {
    id: "ma-clinical-psychology",
    title: "Clinical Psychology",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced clinical psychology program focusing on assessment, diagnosis, and treatment of mental health disorders.",
    features: [
      "Clinical assessment",
      "Therapy techniques",
      "Diagnostic skills",
      "Clinical practice",
      "Thesis option",
    ],
    career: [
      "Clinical Psychologist",
      "Therapist",
      "Mental Health Counselor",
      "Clinical Researcher",
    ],
  },
  {
    id: "ma-law-ms",
    title: "Law",
    category: "graduate",
    degree: "Master's",
    duration: "2 Years",
    description:
      "Advanced legal studies program for legal professionals seeking specialization and advanced legal knowledge.",
    features: [
      "Advanced legal theory",
      "Specialization areas",
      "Legal research",
      "Case analysis",
      "Thesis option",
    ],
    career: [
      "Legal Specialist",
      "Legal Researcher",
      "Legal Advisor",
      "Law Professor",
    ],
  },
  // PhD Programs from ISTU Price List 2025
  {
    id: "phd-aviation-systems-technologies",
    title: "Aviation Systems and Technologies",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral research program in aviation systems and technologies focusing on advanced research and innovation in aerospace.",
    features: [
      "Advanced research",
      "Thesis supervision",
      "Publication support",
      "Conference attendance",
      "Research funding",
    ],
    career: [
      "Aviation Researcher",
      "University Professor",
      "Aerospace Scientist",
      "Research Director",
    ],
  },
  {
    id: "phd-cybersecurity-engineering",
    title: "Cyber Security Engineering",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral program in cybersecurity engineering focusing on advanced security research and innovative security solutions.",
    features: [
      "Security research",
      "Thesis supervision",
      "Publication support",
      "Research funding",
      "Academic mentorship",
    ],
    career: [
      "Security Researcher",
      "University Professor",
      "Security Scientist",
      "Research Director",
    ],
  },
  {
    id: "phd-sports-health-sciences",
    title: "Sports Health Sciences",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral research program in sports health sciences focusing on advanced research in exercise science and sports medicine.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Clinical research",
      "Academic mentorship",
    ],
    career: [
      "Sports Science Researcher",
      "University Professor",
      "Research Scientist",
      "Sports Medicine Specialist",
    ],
  },
  {
    id: "phd-software-engineering",
    title: "Software Engineering",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral program in software engineering focusing on advanced research in software systems and engineering methodologies.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Research projects",
      "Academic mentorship",
    ],
    career: [
      "Software Engineering Researcher",
      "University Professor",
      "Research Scientist",
      "Technical Director",
    ],
  },
  {
    id: "phd-management-information-systems",
    title: "Management Information Systems",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral research program in MIS focusing on advanced research in information systems and business technology.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Research projects",
      "Academic mentorship",
    ],
    career: [
      "MIS Researcher",
      "University Professor",
      "Research Scientist",
      "IT Research Director",
    ],
  },
  {
    id: "phd-management-organization",
    title: "Management and Organization",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral program in management and organization focusing on advanced research in organizational theory and management practices.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Organizational research",
      "Academic mentorship",
    ],
    career: [
      "Management Researcher",
      "University Professor",
      "Organizational Consultant",
      "Research Director",
    ],
  },
  {
    id: "phd-management-engineering",
    title: "Management Engineering",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral research program in management engineering focusing on advanced research in engineering management and systems.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Engineering research",
      "Academic mentorship",
    ],
    career: [
      "Engineering Management Researcher",
      "University Professor",
      "Research Scientist",
      "Engineering Research Director",
    ],
  },
  {
    id: "phd-computer-engineering",
    title: "Computer Engineering",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral program in computer engineering focusing on advanced research in computer systems and hardware design.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Hardware research",
      "Academic mentorship",
    ],
    career: [
      "Computer Engineering Researcher",
      "University Professor",
      "Research Scientist",
      "Hardware Research Director",
    ],
  },
  {
    id: "phd-ai-engineering",
    title: "Artificial Intelligence Engineering",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral research program in AI engineering focusing on advanced research in artificial intelligence and machine learning.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "AI research",
      "Academic mentorship",
    ],
    career: [
      "AI Researcher",
      "University Professor",
      "AI Scientist",
      "Research Director",
    ],
  },
  {
    id: "phd-law",
    title: "Law",
    category: "doctoral",
    degree: "Ph.D.",
    duration: "3-4 Years",
    description:
      "Doctoral program in law focusing on advanced legal research and scholarship in various areas of law.",
    features: [
      "Research funding",
      "Thesis supervision",
      "Publication support",
      "Legal research",
      "Academic mentorship",
    ],
    career: [
      "Legal Researcher",
      "Law Professor",
      "Legal Scholar",
      "Research Director",
    ],
  },
];

export const categories = [
  { id: "all", label: "All Programs" },
  { id: "undergraduate", label: "Undergraduate" },
  { id: "graduate", label: "Graduate" },
  { id: "doctoral", label: "Doctoral" },
  { id: "online", label: "Online" },
  { id: "professional", label: "Professional" },
];
